[versions]
# libraries
annotations = "24.1.0"
jacksonJsr310 = "2.15.2"
tika = "2.9.1"
sshTools = "3.0.11"

# test libraries
junitJupiter = "5.10.0"
junitPlatformLauncher = "1.10.0"
assertj = "3.24.2"
loggingInterceptor = "4.11.0"
mockito = "5.5.0"
remoteRobot = "0.11.21"
checkstyleTools = "10.12.2"

# plugins
dokka = "1.9.10"
kotlin = "1.9.22"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.0"
qodana = "0.1.13"
kover = "0.7.5"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }