[versions]
# libraries
annotations = "24.1.0"
jacksonJsr310 = "2.15.2"
tika = "2.9.1"
sshTools = "3.0.11"

# test libraries
junitJupiter = "5.10.0"
junitPlatformLauncher = "1.10.0"
assertj = "3.24.2"
loggingInterceptor = "4.11.0"
mockito = "5.5.0"
remoteRobot = "0.11.21"
checkstyleTools = "10.12.2"

# plugins
kotlin = "2.0.0"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.3"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }