name: Code Quality
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run Qodana inspections
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2022.1.1
        with:
          fail-threshold: 0

      # Upload Qodana report as GitHub code scanning SARIF file
      - name: Qodana - Upload Github code scanning report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
