name: Code Quality
on:
  workflow_dispatch:
  push:

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Qodana inspections
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2024.1.9

      # Upload Qodana report as GitHub code scanning SARIF file
      - name: Qodana - Upload Github code scanning report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
