name: Run UI Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  ui-tests:
    name: run UI tests for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            runIde: |
              export DISPLAY=:99.0
              Xvfb -ac :99 -screen 0 1920x1080x24 &
              sleep 10
              mkdir -p build/reports
              ./gradlew :runIdeForUiTests > build/reports/idea.log &
            runTests: |
              export DISPLAY=:99.0
              ./gradlew :uiTest
            url: http://127.0.0.1:8082
            reportName: ui-test-fails-report-linux
          - os: macOS-latest
            runIde: |
              mkdir -p build/reports
              ./gradlew :runIdeForUiTests > build/reports/idea.log &
            runTests: ./gradlew :uiTest
            url: http://127.0.0.1:8082
            reportName: ui-test-fails-report-mac
          - os: windows-latest
            runIde: start gradlew.bat :runIdeForUiTests
            runTests: ./gradlew :uiTest
            url: http://localhost:8082
            reportName: ui-test-fails-report-windows

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean
        run: ./gradlew :clean
      - name: Run Idea
        run: ${{ matrix.runIde }}
      - name: Wait for Idea started
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ matrix.url }}
          max-attempts: 15
          retry-delay: 30s
      - name: Tests
        run: ${{ matrix.runTests }}
      - name: Move video
        if: ${{ failure() }}
        run: mv video/ build/reports/
      - name: Copy logs
        if: ${{ failure() }}
        run: mv build/idea-sandbox/system/log/ build/reports
      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.reportName }}
          path: |
            build/reports
